### ISSUE TITLE
버트 모델 컨버전 관련

### ISSUE THREAD

**Issue by kimsijin33** [uoneway/PreSumm_ko#3]
구글 mutilingual BERT 로 만들어진 프로그램을
 koBert 로 전환 가능할까요?

**Comment by uoneway** [comment]
BertSum과 관계 없이 일반적인 경우를 말하시는 건가요?
mutilingual BERT를 명확히 살펴보지 못했었는데 만약 일반적인 BERT와 동일하다면(special token 등),
토크나이저와 모델 부분만 kobert로 바꿔주면 가능하지 않을까 싶습니다.

**Comment by kimsijin33** [comment]
> BertSum과 관계 없이 일반적인 경우를 말하시는 건가요?
> 
> mutilingual BERT를 명확히 살펴보지 못했었는데 만약 일반적인 BERT와 동일하다면(special token 등),
> 
> 토크나이저와 모델 부분만 kobert로 바꿔주면 가능하지 않을까 싶습니다.

답변 감사합니다
